version: '3.5'
services:

  redis:
    image: redis:${REDIS_VERSION}
    hostname: redis
    container_name: docker-redis
    restart: always
    volumes:
      - ${DATA_DIR}/redis:/data:rw
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
    ports:
      - ${REDIS_HOST_PORT}:6379
    extra_hosts:
      - "somehost:162.242.195.82"
    environment:
      - "TZ=${TZ}"
    networks:
      - default

  mongo:
    container_name: docker-mongo
    image: mongo:${MONGODB_VERSION}
    restart: always
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${DATA_DIR}:/data/db
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    networks:
      - default

#  adminmongo:
#    image: mrvautin/adminmongo
#    container_name: docker-adminmongo
#    ports:
#      - "${ADMINMONGO_HOST_PORT}:1234"
#    environment:
#      - HOST=0.0.0.0
#      - DB_HOST=mongodb
#      - DB_PORT=27017
#    networks:
#      - default


  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    container_name: docker-mysql
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/my.cnf:rw
      - ${MYSQL_LOGS_FILE}/mysql:/logs:rw
      - ${DATA_DIR}/mysql:/var/lib/mysql:rw
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${TZ}"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    hostname: rabbitmq
    container_name: docker-rabbitmq
    restart: always
    volumes:
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq
    ports:
      - ${RABBITMQ_HOST_PORT_A}:5672
      - ${RABBITMQ_HOST_PORT_B}:15672
    environment:
      - "RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}"
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}"
    networks:
      - default

  etcd:
      hostname: etcd
      image: bitnami/etcd:3
      container_name: docker-etcd
      restart: always
      ports:
        - "2379:2379"
        - "2380:2380"
        - "4001:4001"
        - "7001:7001"
      user: root
      volumes:
        - ${DATA_DIR}/etcd:/opt/bitnami/etcd/data
      environment:
        - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
        - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
        - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
        - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
        - "ALLOW_NONE_AUTHENTICATION=yes"
        - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
        - "ETCD_NAME=node1"
        - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
      networks:
        - default

networks:
  default:
    driver: bridge
