version: '3'
services:
  redis:
    image: redis:6.0.8
    hostname: redis
    container_name: docker_redis
    volumes:
      - ./redis/data:/data:rw
      - ./redis/conf/redis.conf:/etc/redis/redis.conf:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
    ports:
      - 6379:6379
    networks:
      - brady


  mysql:
    image: mysql:8.0
    hostname: mysql8
    container_name: docker_mysql
    volumes:
      - ./mysql/conf/my.cnf:/etc/my.cnf:rw
      - ./mysql/logs:/logs:rw
      - ./mysql/data:/var/lib/mysql:rw
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=test"
      - "TZ=Asia/Shanghai"
    networks:
      - brady

networks:
  brady:
    driver: bridge