version: '3'
services:

#  redis:
#    image: redis:${REDIS_VERSION}
#    hostname: redis
#    container_name: docker-redis
#    volumes:
#      - ${DATA_DIR}/redis:/data:rw
#      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf:rw
#    command:
#      redis-server /etc/redis/redis.conf --appendonly yes
#    ports:
#      - ${REDIS_HOST_PORT}:6379
#    extra_hosts:
#      - "somehost:162.242.195.82"
#    environment:
#      - "TZ=${TZ}"
#    networks:
#      - default

  nginx:
    image: nginx:1.19.2
    hostname: nginx
    container_name: docker-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    environment:
      - "TZ=${TZ}"
    links:
      - php-fpm
    networks:
      - default

  php-fpm:
    image: php:7.2-fpm
    hostname: nginx
    container_name: docker-php-fpm
    volumes:
      - ./www:/www
    environment:
      - "TZ=${TZ}"
    networks:
      - default

networks:
  default:
    driver: bridge

