version: "3.5"

services:
  mongo:
    container_name: docker-mongo
    image: mongo:${MONGODB_VERSION}
    restart: always
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${DATA_DIR}:/data/db
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    networks:
      - default

  adminmongo:
    image: mrvautin/adminmongo
    container_name: docker-adminmongo
    ports:
      - "${ADMINMONGO_HOST_PORT}:1234"
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mongodb
      - DB_PORT=27017
    networks:
      - default

networks:
  default:
    driver: bridge